---
- name: Create Clients certificate directory
  file:
    path: "{{ openssl_clients_dir }}/{{ item.common_name }}"
    state: directory
    mode: 0600
  with_items: "{{ openssl_clients }}"

- name: Create config file for Clients
  template:
    src: clients-config.cnf.j2
    dest: "{{ openssl_clients_dir }}/{{ item.common_name }}/{{ item.common_name }}.cnf"
    mode: 0640
  with_items: "{{ openssl_clients }}"
  become: true

- name: Create Servers private key and CSR
  command:
    cmd: >
      openssl req -nodes -newkey rsa:2048
      -out {{ item.common_name }}.csr
      -config {{ openssl_clients_dir }}/{{ item.common_name }}/{{ item.common_name }}.cnf
    chdir: "{{ openssl_clients_dir }}/{{ item.common_name }}"
    creates: "{{ openssl_clients_dir }}/{{ item.common_name }}/{{ item.common_name }}.key"
  with_items: "{{ openssl_clients }}"

- name: Create Clients Certificate signed by CA
  command:
    cmd: >
      openssl x509 -req
      -days {{ openssl_clients_cert_expiry }}
      -in {{ openssl_clients_dir }}/{{ item.common_name }}/{{ item.common_name }}.csr
      -CA {{ openssl_ca_dir }}/{{ openssl_ca_cert }}
      -CAkey {{ openssl_ca_dir }}/{{ openssl_ca_key }}
      -CAcreateserial
      -out {{ item.common_name }}.crt
      -passin pass:{{ openssl_secret_ca_passphrase }}
      -extfile {{ openssl_clients_dir }}/{{ item.common_name }}/{{ item.common_name }}.cnf
      -extensions v3_req
    chdir: "{{ openssl_clients_dir }}/{{ item.common_name }}"
    creates: "{{ openssl_clients_dir }}/{{ item.common_name }}/{{item.common_name}}.crt"
  with_items: "{{ openssl_clients }}"
