---
# I need to force cert generation if there is a change in parameter, like expiry
- include: preflight.yml

- include: root-dependencies.yml
  become: true
  when: inventory_hostname in openssl_root

# Create Root CA
- include:  ca-certificate.yml
  become: true
  when: inventory_hostname in openssl_root

# Add Root CA to trust on all hosts
- include: update-ca-trust.yml
  become: true

# Create Server Certificates signed by CA
- include: server-certificate.yml
  become: true
  when: inventory_hostname in openssl_root

# Create Client generation, this will be optional



# # Need to make the copy not dependant on hostname
# # What if i want a seperate cert for postgres and redis ????

# Add Client Certificates to servers
# - include: local-certificate.yml
#   become: true
#   when: inventory_hostname in openssl_clients


