---
- name: Server - Create directory for certificates/keys.
  file:
    path: "{{ openssl_servers_dir }}/{{ item.common_name }}"
    state: directory
    mode: 0600
  with_items: "{{ openssl_servers }}"

- name: Server - Create configuration file
  template:
    src: servers-config.cnf.j2
    dest: "{{ openssl_servers_dir }}/{{ item.common_name }}/{{ item.common_name }}.cnf"
    mode: 0640
  with_items: "{{ openssl_servers }}"
  become: true
  register: _server_cnf


# Force replacement if enabled
- name: Server - Move existing certificates/key if replacement is enabled.
  block:
    - set_fact:
        servers_prefix: "replaced-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"

    - name: Server - Create directory for existing certificates/keys.
      file:
        path: "{{ openssl_servers_dir }}/{{ servers_prefix }}"
        state: directory
        mode: 0600

    - name: Server - Move existing CSR.
      command:
        cmd: mv {{ item.common_name }}.csr {{ servers_prefix }}
        chdir: "{{ openssl_servers_dir }}/{{ item.common_name }}"
      with_items: "{{ openssl_servers }}"
      failed_when: false

    - name: Server - Move existing key.
      command:
        cmd: mv {{ item.common_name }}.key {{ servers_prefix }}
        chdir: "{{ openssl_servers_dir }}/{{ item.common_name }}"
      with_items: "{{ openssl_servers }}"
      failed_when: false

    - name: Server - Move existing certificate.
      command:
        cmd: mv {{ item.common_name }}.crt {{ servers_prefix }}
        chdir: "{{ openssl_servers_dir }}/{{ item.common_name }}"
      with_items: "{{ openssl_servers }}"
      failed_when: false
  when: _server_cnf.changed or openssl_servers_force_replace or openssl_ca_force_replace


- name: Server - Create private key and CSR.
  command:
    cmd: >
      openssl req -nodes -newkey rsa:2048
      -out {{ item.common_name }}.csr
      -config {{ openssl_servers_dir }}/{{ item.common_name }}/{{ item.common_name }}.cnf
    chdir: "{{ openssl_servers_dir }}/{{ item.common_name }}"
    creates: "{{ openssl_servers_dir }}/{{ item.common_name }}/{{ item.common_name }}.key"
  with_items: "{{ openssl_servers }}"


- name: Server - Create Certificate signed by CA.
  command:
    cmd: >
      openssl x509 -req
      -days {{ openssl_servers_cert_expiry }}
      -in {{ openssl_servers_dir }}/{{ item.common_name }}/{{ item.common_name }}.csr
      -CA {{ openssl_ca_dir }}/{{ openssl_ca_cert }}
      -CAkey {{ openssl_ca_dir }}/{{ openssl_ca_key }}
      -CAcreateserial
      -out {{ item.common_name }}.crt
      -passin pass:{{ openssl_secret_ca_passphrase }}
      -extfile {{ openssl_servers_dir }}/{{ item.common_name }}/{{ item.common_name }}.cnf
      -extensions v3_req
    chdir: "{{ openssl_servers_dir }}/{{ item.common_name }}"
    creates: "{{ openssl_servers_dir }}/{{ item.common_name }}/{{item.common_name}}.crt"
  with_items: "{{ openssl_servers }}"
