---
- name: Fetch CA from root
  fetch:
    src:  "{{ openssl_ca_dir }}/{{ openssl_ca_cert }}"
    dest: /tmp/
    flat: True
  when: inventory_hostname in openssl_root

- name: Make sure anchor directory exists
  file:
    path: "{{ openssl_clients_ca_dir }}"
    state: directory
    mode: 0755

- name: Add CA file
  copy:
    src: /tmp/{{ openssl_ca_cert }}
    dest: "{{ openssl_clients_ca_dir }}/{{ openssl_clients_ca_file }}"
  register: _client_ca

- name: Update CA Trust
  block:

  - name: RedHat - Update CA trust
    command: update-ca-trust extract && update-ca-trust
    when: ansible_os_family == "RedHat"

  - name: Debian - Update CA trust
    command: update-ca-certificates
    when: ansible_os_family == "Debian"

  when: _client_ca.changed