---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        openssl_servers:
          - common_name: server.example.com
        openssl_clients:
          - common_name: client@example.com

  roles:
    # - role: ansible-private-tls
    - role: private-tls
      tags:
        - private-tls
